version: '3.8'

services:
  redmine:
    image: redmine:4.2.10-bullseye
    container_name: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: redmine-db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine_user
      REDMINE_DB_PASSWORD: redmine_passwd
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_DB_PORT: 5432
    volumes:
      - ./files:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins

  redmine-db:
    image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine_user
      POSTGRES_PASSWORD: redmine_passwd
    volumes:
      - vol_redmine_db:/var/lib/postgresql/data

volumes:
  vol_redmine_db:
